### PR TITLE
Fixed spellings in autoui_widget_viewer.upynb and stellarphot/core.py

### PR DESCRIPTION
**Pull request by JuanCab**
This PR fixes a bunch of typos (and in some cases, troublesome variable names that are confused for typos) that were caught by codespell.  This should reduce the number of failed codespell checks dramatically. :). 

I also updated `ignore-words.txt` to not flag some words we legitimately misspell. :)

### CODE REVIEW

**Comment by mwcraig** [comment]
@JuanCab -- can you try rebasing this to remove the conflict? Not sure why none of the tests are running either...

**Comment by mwcraig** [comment]
Looks like there is still one spelling error....

**Comment by JuanCab** [comment]
Not sure why that happened, but things are fixed and I suspect this will will now pass the tests.  In the process of fixing the merge, I discovered one file failing the codespell check, so that has been fixed as well.

**Review by mwcraig — APPROVED** [review]
Looks good!

**Pull request merged**
