### PR TITLE
Fix "Edit" button issues

### PR DESCRIPTION
**Pull request by mwcraig**
This PR addresses the edit button issues mentioned in #303. The other issues will be addressed in a separate PR.

### CODE REVIEW

**Comment by Tanner728** [comment]
I will be at tutoring for the next few hours but will have a chance to take a look later tonight.

**Comment by Tanner728** [comment]
Hello, after some testing I found a weird bug. 
The bug is the `edit this observatory` button disappears. 
The steps that I did to cause this were as follows. 
1. Create a valid observatory.
2. Switch the menu to `Make a new Observatory`. 
3. Switch back to the observatory you had previously created. 

Now the `Edit this observatory button` should not appear and you are unable to edit the observatory. To fix this you can just recreate the menu but the issue appears every time you follow those steps. 

image

**Comment by mwcraig** [comment]
Thanks @Tanner728 -- I think I have fixed that now.

**Review by JuanCab — APPROVED** [review]
Tests looks reasonable.

**Review by Tanner728 — APPROVED** [review]
I have not been able to find anymore bugs with the UI at this point.

**Pull request merged**
