### PR TITLE
Switch to the pydata sphinx theme

### PR DESCRIPTION
**Pull request by mwcraig**
This theme was recently adopted by astropy and is pretty widely used by other large projects. Seemed better to switch pre-release rather than post-release.

Marking this as a draft for now because ~~I need to copy over some CSS from astropy, I think...~~

Copied that over, still want to look at how they do the card setup here: astropy.rtfd.io

### CODE REVIEW

**Comment by mwcraig** [comment]
The test failure here is fixed in #258

**Comment by mwcraig** [comment]
Rebased to pull in #258. 

I think further changes should wait until documentation is actually drafted. It looks like the pydata Sphinx theme has [lots of customization options](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/layout.html#), for better or worse....

Best thing is that it has a dark mode 😀

**Comment by JuanCab** [comment]
> To see a rendered version of the documentation click on the "Details" link for the ReadTheDocs check.

Can you clarify what you mean here?  I created a copy of the docs with tox but did you want me to check something else?

**Review by JuanCab — COMMENTED** [review]
The only issue I see is when I brought up the HTML pages generated using `tox -e build_docs`, they had a dark background which made seeing the inheritance diagrams difficult.  Might need some CSS tweaked.

**Comment by mwcraig** [comment]
> Can you clarify what you mean here? I created a copy of the docs with tox but did you want me to check something else?

I meant this -- the documentation gets built on ReadTheDocs for every pull request :grinning::

Switch_to_the_pydata_sphinx_theme_by_mwcraig_·_Pull_Request__259_·_feder-observatory_stellarphot

**Comment by mwcraig** [comment]
> dark background which made seeing the inheritance diagrams difficult. Might need some CSS tweaked.

Looking into it...

**Comment by mwcraig** [comment]
I'm seeing legible inheritance diagrams on RTD, though they look different to me locally, investigating that...

stellarphot_Documentation_—_stellarphot_v0_1_dev222_g9fc662c_d20240115

**Comment by mwcraig** [comment]
No idea why the build looks the way it should on RTD but not locally 🤷‍♂️

**Comment by mwcraig** [comment]
I'm going to merge this so that I can do some documentation work today or tomorrow. Still not quite sure what is up with the inheritance diagrams locally, but since it works on RTD I figure that is good enough.

**Pull request merged**
